export type Theme = {
  name: string;
  vibe: string;
  ink: string;
  accent: string;
  paper: string;
  surface: string;
  font: string; // CSS variable set in lib/fonts.ts, e.g. "var(--font-cute)"
  weight: number; // headline weight for this typeface
  shape: string;
  pattern: "none" | "dots" | "grid" | "lines" | "halftone" | "confetti";
};

export const themes: Theme[] = [
  {
    name: "Cute",
    vibe: "Soft & sunny",
    ink: "#5b2a46",
    accent: "#ff8fbe",
    paper: "#fff7fb",
    surface: "#5b2a46",
    font: "var(--font-cute)",
    weight: 700,
    shape: "22px",
    pattern: "dots",
  },
  {
    name: "Cool",
    vibe: "Electric current",
    ink: "#0e2a52",
    accent: "#5b8def",
    paper: "#f3f7ff",
    surface: "#0e2a52",
    font: "var(--font-cool)",
    weight: 600,
    shape: "6px",
    pattern: "grid",
  },
  {
    name: "Classic",
    vibe: "Timeless ledger",
    ink: "#2b2620",
    accent: "#b4894f",
    paper: "#fbf6e9",
    surface: "#3d372f",
    font: "var(--font-classic)",
    weight: 700,
    shape: "0px",
    pattern: "none",
  },
  {
    name: "Modern",
    vibe: "Clean contrast",
    ink: "#121212",
    accent: "#c6f24b",
    paper: "#ffffff",
    surface: "#121212",
    font: "var(--font-modern)",
    weight: 800,
    shape: "10px",
    pattern: "none",
  },
  {
    name: "Editorial",
    vibe: "Ink & margin",
    ink: "#2e2a57",
    accent: "#b7a6ff",
    paper: "#f7f5ff",
    surface: "#2e2a57",
    font: "var(--font-editorial)",
    weight: 500,
    shape: "0px",
    pattern: "lines",
  },
  {
    name: "Retro",
    vibe: "Peachy nostalgia",
    ink: "#6e3c2f",
    accent: "#ffae5c",
    paper: "#fff1dc",
    surface: "#6e3c2f",
    font: "var(--font-retro)",
    weight: 800,
    shape: "16px",
    pattern: "dots",
  },
  {
    name: "Minimal",
    vibe: "Quiet essentials",
    ink: "#454545",
    accent: "#cfcfcf",
    paper: "#fafafa",
    surface: "#454545",
    font: "var(--font-minimal)",
    weight: 500,
    shape: "3px",
    pattern: "none",
  },
  {
    name: "Botanical",
    vibe: "Greenhouse hush",
    ink: "#22392a",
    accent: "#86b96a",
    paper: "#f2f6ec",
    surface: "#22392a",
    font: "var(--font-botanical)",
    weight: 600,
    shape: "8px",
    pattern: "lines",
  },
  {
    name: "Noir",
    vibe: "Midnight & gold",
    ink: "#f2ece0",
    accent: "#d8b25c",
    paper: "#171512",
    surface: "#000000",
    font: "var(--font-noir)",
    weight: 500,
    shape: "2px",
    pattern: "none",
  },
  {
    name: "Pastel",
    vibe: "Cotton-candy calm",
    ink: "#4a3b5c",
    accent: "#c9b6ff",
    paper: "#faf7ff",
    surface: "#4a3b5c",
    font: "var(--font-pastel)",
    weight: 700,
    shape: "18px",
    pattern: "dots",
  },
  {
    name: "Sunset",
    vibe: "Coral horizon",
    ink: "#5c2a1f",
    accent: "#ff7a59",
    paper: "#fff3ea",
    surface: "#5c2a1f",
    font: "var(--font-sunset)",
    weight: 600,
    shape: "14px",
    pattern: "grid",
  },
  {
    name: "Thermal",
    vibe: "Register tape",
    ink: "#1a1a1a",
    accent: "#1a1a1a",
    paper: "#ffffff",
    surface: "#1a1a1a",
    font: "var(--font-thermal)",
    weight: 500,
    shape: "0px",
    pattern: "lines",
  },
  {
    name: "Newsprint",
    vibe: "Broadsheet ink",
    ink: "#1d1d1d",
    accent: "#c1121f",
    paper: "#f1eee6",
    surface: "#1d1d1d",
    font: "var(--font-newsprint)",
    weight: 600,
    shape: "0px",
    pattern: "halftone",
  },
  {
    name: "Terrazzo",
    vibe: "Confetti stone",
    ink: "#38313f",
    accent: "#e8615a",
    paper: "#f6f1ec",
    surface: "#38313f",
    font: "var(--font-terrazzo)",
    weight: 700,
    shape: "20px",
    pattern: "confetti",
  },
  {
    name: "Citrus",
    vibe: "Zesty morning",
    ink: "#3b2b00",
    accent: "#ffc93c",
    paper: "#fffbf0",
    surface: "#3b2b00",
    font: "var(--font-citrus)",
    weight: 600,
    shape: "12px",
    pattern: "none",
  },
  {
    name: "Slate",
    vibe: "Studio grey",
    ink: "#1f2430",
    accent: "#7c8ca6",
    paper: "#f4f5f7",
    surface: "#1f2430",
    font: "var(--font-slate)",
    weight: 500,
    shape: "4px",
    pattern: "grid",
  },
];